[dependencies]
base = "0.11.1"

[package]
name = "xtended-numbers"
version = "0.3.1"
description = "Extended functionality for motoko number types, such as byte encoding"
repository = "https://github.com/edjCase/motoko_numbers"
keywords = [ "numbers" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
